sonar.projectKey=patriciamrs_prova03-e2e-PatriciaMorais
sonar.organization=patriciamrs
sonar.projectName=prova03-e2e-PatriciaMorais
sonar.projectVersion=1.0
sonar.sources=./src
sonar.sourceEncoding=UTF-8